FILE_EXTENSIONS = {
    '.txt', '.rtf', '.md', '.odt', '.wps', '.wpd', '.log', '.nfo',
    '.doc', '.docx', '.xls', '.xlsx', '.ppt', '.pptx', '.csv', '.mdb',
    '.accdb', '.pub', '.vsd', '.msg', '.one', '.xps', '.epub', '.mobi',
    '.tex', '.ltx', '.pdf', '.psd', '.ai', '.indd', '.eps', '.prproj',
    '.aep', '.fla', '.swf', '.html', '.htm', '.css', '.js', '.json',
    '.xml', '.php', '.asp', '.aspx', '.jsp', '.rss', '.atom', '.xhtml',
    '.webmanifest', '.woff', '.woff2', '.eot', '.ttf', '.otf', '.svg',
    '.jpg', '.jpeg', '.png', '.gif', '.bmp', '.tiff', '.tif', '.ico',
    '.webp', '.heif', '.heic', '.raw', '.dng', '.cr2', '.nef', '.orf',
    '.sr2', '.icns', '.exr', '.mp3', '.wav', '.aac', '.flac', '.ogg',
    '.wma', '.m4a', '.aiff', '.aif', '.opus', '.mp4', '.mov', '.avi',
    '.wmv', '.flv', '.webm', '.mkv', '.3gp', '.mpeg', '.mpg', '.m4v',
    '.mts', '.ts', '.vob', '.zip', '.rar', '.7z', '.tar', '.gz', '.bz2',
    '.xz', '.iso', '.img', '.vhd', '.vhdx', '.ova', '.ovf', '.cab',
    '.zst', '.dmgpart', '.sparseimage', '.exe', '.dll', '.sys', '.msi',
    '.dmg', '.apk', '.deb', '.rpm', '.bin', '.sh', '.bat', '.cmd',
    '.ps1', '.kext', '.efi', '.scr', '.py', '.java', '.c', '.cpp',
    '.cxx', '.cc', '.h', '.hpp', '.cs', '.rb', '.pl', '.go', '.swift',
    '.kt', '.ts', '.jsx', '.tsx', '.vue', '.rs', '.scala', '.groovy',
    '.m', '.sql', '.jsonc', '.yml', '.yaml', '.toml', '.conf', '.cfg',
    '.ini', '.env', '.lock', '.ipynb', '.r', '.rmd', '.jl', '.dart',
    '.sln', '.csproj', '.vcxproj', '.nix', '.bazel', '.bzl', '.make',
    '.mk', '.gitattributes', '.gitignore', '.gitmodules', '.fon',
    '.fnt', '.pfb', '.pfm', '.dwg', '.dxf', '.stl', '.obj', '.fbx',
    '.blend', '.gcode', '.3mf', '.db', '.sqlite', '.sqlite3', '.ldb',
    '.dat', '.binlog', '.eml', '.emlx', '.ics', '.torrent', '.url',
    '.lnk', '.crdownload', '.part', '.vbs', '.wsf', '.reg', '.bak',
    '.tmp'
}
